(when (locate-library "direx")
  (require 'direx)
  (push '(direx:direx-mode :position left :width 40 :dedicated t)
        popwin:special-display-config)
  (global-set-key (kbd "C-x j") 'direx:jump-to-directory-other-window)
  )
